const eng = {
    "Our_products" : "Our products",
    "Check_code": "Check code",
    "About_us": "About us",
    "Cooperation": "Cooperation",
    "Contacts": "Contacts",
    "owl-carousel__title": "Lorem ipsum dolor sit amet",
    "owl-carousel__descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos accusamus quo deserunt reiciendis nihil voluptas molestias placeat fugit, nesciunt dicta magnam. Earum aliquid illum aperiam quasi deserunt, optio iusto perferendis.",
    "add_in_basket": "Add in basket",
    "Fast_sending": "Fast sending",
    "Fast_sending_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet eaque maiores cupiditate quaerat soluta neque sunt temporibus fugit omnis quis voluptatibus nulla, atque nihil. Est saepe praesentium cupiditate quia? Laborum?",
    "Quality_assurance": "Quality assurance",
    "Quality_assurance_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet eaque maiores cupiditate quaerat soluta neque sunt temporibus fugit omnis quis voluptatibus nulla, atque nihil. Est saepe praesentium cupiditate quia? Laborum?",
    "Professionals_in_their_field": "Professionals in their field",
    "Professionals_in_their_field_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet eaque maiores cupiditate quaerat soluta neque sunt temporibus fugit omnis quis voluptatibus nulla, atque nihil. Est saepe praesentium cupiditate quia? Laborum?",
    "Contests_and_promotions": "Contests and promotions",
    "Fast_sending_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet eaque maiores cupiditate quaerat soluta neque sunt temporibus fugit omnis quis voluptatibus nulla, atque nihil. Est saepe praesentium cupiditate quia? Laborum?",
    "catalog_ours_produtions": "Catalog ours produtions",
    "carousel__amount": "Quantity: 1 bottle 5 ml",
    "owl-carousel__amount_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, quia. Autem, rem. Corrupti, expedita ratione saepe aliquid sit voluptate vero tenetur aperiam dolores! Repellat ea libero, quis doloribus consequatur doloremque.",
    "benefits": "Benefits",
    "check-desrc": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, quia. Autem, rem. Corrupti, expedita ratione saepe aliquid sit voluptate vero tenetur aperiam dolores!",
    "owl-carousel__title-price": "Price:",
    "quality__title": "Why choose our products?",
    "quality__text": "Quality",
    "quality__subtitle": "Quality standards",
    "quality__descr": "The product is manufactured in the Russian Federation according to international quality standards.",
    "identity__title": "Product authentication",
    "identity__subtitle": "Enter the code from the label on the vial",
    "identity__descr": "In case of an error, please inform us by mail – <a href='mailto:info@grain-bio.com'>info@grain-bio.com</a>",
    "btn__identity": "Verify",
    "form_identity__text_check": "Verification was successful!",
    "form_identity__text_not-check": "Error in code, please try again.",
    "form_question__title": "Still have questions?",
    "form_question__descr": "Fill out the form and get a <br/> <span> free </span> expert consultation",
    "btn__question": "Send message",
    "form_footer__title": "Subscribe to notifications about promotions and new products",
    "subscribe": "Subscribe",
    "years": "© 2020",
    // for placeholder
    "Введите имя":"Enter your name",
    "Введите почту" : "Enter mail",
    "Сообщение" : "Message",
    "Введите ваш e-mail" : "Enter your e-mail",
    "XUQ-SSC-YSGE" : "XUQ-SSC-YSGE",
};
