const rus = {
    "Our_products" : "Наша продукция",
    "Check_code": "Проверить код",
    "About_us": "О нас",
    "Cooperation": "Сотрудничество",
    "Contacts": "Контакты",
    "owl-carousel__title": "Lorem ipsum dolor sit amet",
    "owl-carousel__descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Eos accusamus quo deserunt reiciendis nihil voluptas molestias placeat fugit, nesciunt dicta magnam. Earum aliquid illum aperiam quasi deserunt, optio iusto perferendis.",
    "add_in_basket": "Добавить в корзину",
    "Fast_sending": "Быстрая отправка",
    "Fast_sending_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet eaque maiores cupiditate quaerat soluta neque sunt temporibus fugit omnis quis voluptatibus nulla, atque nihil. Est saepe praesentium cupiditate quia? Laborum?",
    "Quality_assurance": "Гарантия качества",
    "Quality_assurance_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet eaque maiores cupiditate quaerat soluta neque sunt temporibus fugit omnis quis voluptatibus nulla, atque nihil. Est saepe praesentium cupiditate quia? Laborum?",
    "Professionals_in_their_field": "Профессионалы своего дела",
    "Professionals_in_their_field_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet eaque maiores cupiditate quaerat soluta neque sunt temporibus fugit omnis quis voluptatibus nulla, atque nihil. Est saepe praesentium cupiditate quia? Laborum?",
    "Contests_and_promotions": "Конкурсы и акции",
    "Fast_sending_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet eaque maiores cupiditate quaerat soluta neque sunt temporibus fugit omnis quis voluptatibus nulla, atque nihil. Est saepe praesentium cupiditate quia? Laborum?",
    "catalog_ours_produtions": "Каталог нашей продукции",
    "carousel__amount": "Количество: 1 флакон 5 мл",
    "owl-carousel__amount_descr": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, quia. Autem, rem. Corrupti, expedita ratione saepe aliquid sit voluptate vero tenetur aperiam dolores! Repellat ea libero, quis doloribus consequatur doloremque.",
    "benefits": "Приемущества",
    "check-desrc": "Lorem ipsum dolor sit amet consectetur adipisicing elit. Totam, quia. Autem, rem. Corrupti, expedita ratione saepe aliquid sit voluptate vero tenetur aperiam dolores!",
    "owl-carousel__title-price": "Цена:",
    "quality__title": "Почему выбирают нашу продукцию?",
    "quality__text": "качество",
    "quality__subtitle": "Стандарты качества",
    "quality__descr": "Продукт производится на территории Российской Федерации, по международным стандартам качества.",
    "identity__title": "Проверка подлинности продукта",
    "identity__subtitle": "Введите код с наклейки на виале",
    "identity__descr": "В случае ошибки, сообщите об этом нам по почте – <a href='mailto:info@grain-bio.com'>info@grain-bio.com</a>",
    "btn__identity": "Проверить",
    "form_identity__text_check": "Проверка прошла успешно!",
    "form_identity__text_not-check": "Ошибка в коде, попробуйте еще раз.",
    "form_question__title": "Остались вопросы?",
    "form_question__descr": "Заполните форму и получите <br/>       <span>бесплатную</span> консультацию специалиста",
    "btn__question": "Отправить",
    "form_footer__title": "Подписаться на уведомления об акциях и поступлении новой продукции",
    "subscribe": "Подписаться",
    "years": "2020 г. ©",
    // for placeholder
    "Enter your name" : "Введите имя",
    "Enter mail" : "Введите почту",
    "Message" : "Сообщение",
    "Enter your e-mail" : "Введите ваш e-mail",
    "XUQ-SSC-YSGE" : "XUQ-SSC-YSGE",
};
